// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmanzxxutiflouktnjgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtYW56eHh1dGlmbG91a3Ruamd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MTUwNzQsImV4cCI6MjA2NDM5MTA3NH0.GJmFPwCCPvAj-KuScP1We8Ls06VDTE9OJINg5Sj16tU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);